// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pssdmcfjxsfhxoaadtvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzc2RtY2ZqeHNmaHhvYWFkdHZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDA3NDA5MjYsImV4cCI6MjAxNjMxNjkyNn0.Gdyl5mzRnvhm064wk5Gzo-bvsd1eC0O1Q-ilULCXsKI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);